name: Lista Lending
icon: logo.png
category: Money Market
url: https://lista.org/lending
description: >-
  Redefining BNB with Liquid Staking, Lista Lending and CDP Solutions
metadata:
  pt:
    - chainId: 56
      address: '0x67e84ba0196738a59ee58df848a2c16ed2a6a6f3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xdee403936c6f4c64095e68301c0b5ea2d49fa36ed204b61d504f55b280079a36
      description: >-
        PT-USDe-9APR2026(PLASMA) can be used as collateral to borrow or multiply
        against USD1
      subtitle: USD1
    - chainId: 56 
      address: '0x7EB92A12a15E8a019A26A8b344F1e59b14cb8Ad3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xcde129c808d3b7f57fa2384e5ceb1d3debb0c895932f06364abb9d6760a1e6e7
      description: >-
        PT-sUSDe-9APR2026(PLASMA) can be used as collateral to borrow or multiply
        against USDT    
      subtitle: USDT
    - chainId: 56
      address: '0x7EB92A12a15E8a019A26A8b344F1e59b14cb8Ad3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x73a49d7e15386803327e0571908259b1ebd9c5638f91b90545fdda7694c8a3a2
      description: >-
        PT-sUSDe-9APR2026(PLASMA) can be used as collateral to borrow or multiply
        against USD1       
      subtitle: USD1
    - chainId: 56
      address: '0x7EB92A12a15E8a019A26A8b344F1e59b14cb8Ad3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x8f67e40a16183fb211df70012365f6f4c6e1b90373659ee72749d6152b85dd7f
      description: >-
        PT-sUSDe-9APR2026(PLASMA) can be used as collateral to borrow or multiply
        against U 
      subtitle: U
    - chainId: 56
      address: '0x0EA46a4C257071352b57E9F6d054fC137F6E14b9'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x62bd656d4c1896dec061ceab413bedf3a1cc713c5134bbd6c6d58099cae07284
      description: >-
        PT-srUSDe-2APR2026(ETH) can be used as collateral to borrow or multiply
        against U 
      subtitle: U
    - chainId: 56
      address: '0x0EA46a4C257071352b57E9F6d054fC137F6E14b9'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x0ff603ab5cf4b44e603ec8109acf7b84f36133278b9f20ca404d216e593d0964
      description: >-
        PT-srUSDe-2APR2026(ETH) can be used as collateral to borrow or multiply
        against USDT
      subtitle: USDT
  yt: []
  lp: []
