name: Lista Lending
icon: logo.png
category: Money Market
url: https://lista.org/lending
description: Redefining BNB with Liquid Staking, Lista Lending and CDP Solutions
metadata:
  pt:
    - chainId: 56
      address: '0x7EB92A12a15E8a019A26A8b344F1e59b14cb8Ad3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x8f67e40a16183fb211df70012365f6f4c6e1b90373659ee72749d6152b85dd7f
      description: >-
        PT-sUSDe-9APR2026(PLASMA) can be used as collateral to borrow or
        multiply against U 
      subtitle: U
    - chainId: 56
      address: '0xe052823b4aefc6e230faf46231a57d0905e30ae0'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x02e3e78089e25120193128aac38cb28a6d9ef4d8aba8134a9235100f699ab26b
      description: >-
        PT-clisBNB-25JUN2026 can be used as collateral to borrow or multiply
        against BNB
      subtitle: BNB
    - chainId: 56
      address: '0x7e318884f6f299031f4fa88d7a324e076d460a4b'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x4d5db69438f73d026b81cda3d6263a32c3ea9a4b0a28d3d3be1ab9aec8a996cc
      description: >-
        PT-USDe-7MAY2026 can be used as collateral to borrow or multiply against
        USD1
      subtitle: USD1
    - chainId: 56
      address: '0x67e84ba0196738a59ee58df848a2c16ed2a6a6f3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x3b4a64c5d230773d31440dee7f98245784b362130baca089b9ea81a777628746
      description: >-
        PT-USDe-9APR2026 can be used as collateral to borrow or multiply against
        USDT
      subtitle: USDT
    - chainId: 56
      address: '0x67e84ba0196738a59ee58df848a2c16ed2a6a6f3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xdee403936c6f4c64095e68301c0b5ea2d49fa36ed204b61d504f55b280079a36
      description: >-
        PT-USDe-9APR2026 can be used as collateral to borrow or multiply against
        USD1
      subtitle: USD1
    - chainId: 56
      address: '0x7eb92a12a15e8a019a26a8b344f1e59b14cb8ad3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x73a49d7e15386803327e0571908259b1ebd9c5638f91b90545fdda7694c8a3a2
      description: >-
        PT-sUSDE-9APR2026 can be used as collateral to borrow or multiply
        against USD1
      subtitle: USD1
    - chainId: 56
      address: '0x7eb92a12a15e8a019a26a8b344f1e59b14cb8ad3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xcde129c808d3b7f57fa2384e5ceb1d3debb0c895932f06364abb9d6760a1e6e7
      description: >-
        PT-sUSDE-9APR2026 can be used as collateral to borrow or multiply
        against USDT
      subtitle: USDT
  yt: []
  lp: []
