name: Rezerve Money
icon: logo.png
category: Yield Strategy
url: https://rezerve.money/
description: >-
  Rezerve Money is a yield strategy protocol that combines dynamic rebasing, staking, bonding, and liquid staking mechanisms.