name: Pulse
icon: logo.png
category: Yield Strategy
url: https://www.usepulse.xyz/
description: Pulse does it all. Scanning PT markets, reallocating capital, compounding returns, rolling maturities, and maximizing yield across Pendle.