name: Euler
icon: logo.png
category: Money Market
url: https://app.euler.finance/borrow?network=ethereum
description: >-
  Euler is a modular lending platform that enables users to lend, borrow and
  build without limits.
metadata:
  pt:
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      subtitle: hgETH
      relatedAsset: '0x3f714090f7648139043349f599a48904187d76d0'
      integrationUrl: >-
        https://app.euler.finance/positions/0x18337806b02b02099209b05589e6db85acd4345c/0x3f714090f7648139043349f599a48904187d76d0?network=ethereum
      description: >-
        The PT-hgETH-25JUN2026 is the asset used as collateral in an Euler
        market with ehgETH-2 as the loan token.
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      subtitle: WETH
      relatedAsset: '0x87c414825ab3d1e9bdc773e9b1fd968822c9cf51'
      integrationUrl: >-
        https://app.euler.finance/positions/0x18337806b02b02099209b05589e6db85acd4345c/0x87c414825ab3d1e9bdc773e9b1fd968822c9cf51?network=ethereum
      description: >-
        The PT-hgETH-25JUN2026 is the asset used as collateral in an Euler
        market with eWETH-29 as the loan token.
    - chainId: 8453
      address: '0x0177055f7429d3bd6b19f2dd591127db871a510e'
      subtitle: USDC
      relatedAsset: '0x085178078796da17b191f9081b5e2fccc79a7ee7'
      integrationUrl: >-
        https://app.euler.finance/positions/0x24d633664aea3f551b2fa34fa66dd1ba52a33933/0x085178078796da17b191f9081b5e2fccc79a7ee7?network=base
      description: >-
        The PT-yoUSD-26MAR2026 is the asset used as collateral in an Euler
        market with eUSDC-29 as the loan token.
    - chainId: 8453
      address: '0x0177055f7429d3bd6b19f2dd591127db871a510e'
      subtitle: yoUSD
      relatedAsset: '0x990d616ca6e7192625d1b7c41fb67b5758df7cf2'
      integrationUrl: >-
        https://app.euler.finance/positions/0x24d633664aea3f551b2fa34fa66dd1ba52a33933/0x990d616ca6e7192625d1b7c41fb67b5758df7cf2?network=base
      description: >-
        The PT-yoUSD-26MAR2026 is the asset used as collateral in an Euler
        market with eyoUSD-1 as the loan token.
    - chainId: 8453
      address: '0x1a5c5ea50717a2ea0e4f7036fb289349deaab58b'
      subtitle: WETH
      relatedAsset: '0x774c08f8e78c47046d325c0331788954c35df10a'
      integrationUrl: >-
        https://app.euler.finance/positions/0x38df63f1986b80578b7357bcda3d4f71f129afff/0x774c08f8e78c47046d325c0331788954c35df10a?network=base
      description: >-
        The PT-yoETH-26MAR2026 is the asset used as collateral in an Euler
        market with eWETH-19 as the loan token.
    - chainId: 8453
      address: '0x1a5c5ea50717a2ea0e4f7036fb289349deaab58b'
      subtitle: yoETH
      relatedAsset: '0xdbdc9c3edbd401109c83b333c16a0251806b3330'
      integrationUrl: >-
        https://app.euler.finance/positions/0x38df63f1986b80578b7357bcda3d4f71f129afff/0xdbdc9c3edbd401109c83b333c16a0251806b3330?network=base
      description: >-
        The PT-yoETH-26MAR2026 is the asset used as collateral in an Euler
        market with eyoETH-1 as the loan token.
    - chainId: 9745
      address: '0xd516188daf64efa04a8d60872f891f2cc811a561'
      subtitle: USDai
      relatedAsset: '0x8539f99dbc4f437c1f71de6920369b9cd46193ff'
      integrationUrl: >-
        https://app.euler.finance/positions/0x5dcce5f1eddf4c1ada8bcf2da89d4bc7fb9dd5d2/0x8539f99dbc4f437c1f71de6920369b9cd46193ff?network=plasma
      description: >-
        The PT-USDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDai-2 as the loan token.
    - chainId: 9745
      address: '0xd516188daf64efa04a8d60872f891f2cc811a561'
      subtitle: USDT0
      relatedAsset: '0x98d6863fa1c247d529c94e53f521897ae9a6ebf0'
      integrationUrl: >-
        https://app.euler.finance/positions/0x5dcce5f1eddf4c1ada8bcf2da89d4bc7fb9dd5d2/0x98d6863fa1c247d529c94e53f521897ae9a6ebf0?network=plasma
      description: >-
        The PT-USDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDT0-17 as the loan token.
    - chainId: 9745
      address: '0x48f119b3fca8244274531f2e06b74ac4b1f5fe58'
      subtitle: RLP
      relatedAsset: '0x9cbadf620185f98dd61241242089ff5f960adcb8'
      integrationUrl: >-
        https://app.euler.finance/positions/0x0fbde49d0c6fa71d097c3c6465ecd6fb49ac7efa/0x9cbadf620185f98dd61241242089ff5f960adcb8?network=plasma
      description: >-
        The PT-RLP-26FEB2026 is the asset used as collateral in an Euler market
        with eRLP-2 as the loan token.
    - chainId: 9745
      address: '0x48f119b3fca8244274531f2e06b74ac4b1f5fe58'
      subtitle: USDT0
      relatedAsset: '0xb23377af59d4fc95cb8330ee2834aa8241eeed03'
      integrationUrl: >-
        https://app.euler.finance/positions/0x0fbde49d0c6fa71d097c3c6465ecd6fb49ac7efa/0xb23377af59d4fc95cb8330ee2834aa8241eeed03?network=plasma
      description: >-
        The PT-RLP-26FEB2026 is the asset used as collateral in an Euler market
        with eUSDT0-40 as the loan token.
    - chainId: 9745
      address: '0xffaf49f320b8ae1bb9ea596197040077a3666105'
      subtitle: USR
      relatedAsset: '0x1b44853e7c3b6acba72c0b05e08b1f6aa029ff15'
      integrationUrl: >-
        https://app.euler.finance/positions/0x4982576311a80a3d40ac5b97195f1de6c8c879c8/0x1b44853e7c3b6acba72c0b05e08b1f6aa029ff15?network=plasma
      description: >-
        The PT-wstUSR-26FEB2026 is the asset used as collateral in an Euler
        market with eUSR-3 as the loan token.
    - chainId: 9745
      address: '0xffaf49f320b8ae1bb9ea596197040077a3666105'
      subtitle: USDT0
      relatedAsset: '0x6a9e59545169be88115671d7171967f8fbffa0cd'
      integrationUrl: >-
        https://app.euler.finance/positions/0x4982576311a80a3d40ac5b97195f1de6c8c879c8/0x6a9e59545169be88115671d7171967f8fbffa0cd?network=plasma
      description: >-
        The PT-wstUSR-26FEB2026 is the asset used as collateral in an Euler
        market with eUSDT0-41 as the loan token.
    - chainId: 9745
      address: '0xedac81b27790e0728f54dea3b7718e5437e85353'
      subtitle: USDT0
      relatedAsset: '0x66ab62571ccd31d911eeefea85944895e30c0a3a'
      integrationUrl: >-
        https://app.euler.finance/positions/0xce7120c69a77e90615a9d65c581fdac1fd311cdc/0x66ab62571ccd31d911eeefea85944895e30c0a3a?network=plasma
      description: >-
        The PT-sUSDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDT0-18 as the loan token.
    - chainId: 9745
      address: '0xedac81b27790e0728f54dea3b7718e5437e85353'
      subtitle: USDai
      relatedAsset: '0x4bfcf2acc5cb79ee2a00d08edfb81efd37cc2fe5'
      integrationUrl: >-
        https://app.euler.finance/positions/0xce7120c69a77e90615a9d65c581fdac1fd311cdc/0x4bfcf2acc5cb79ee2a00d08edfb81efd37cc2fe5?network=plasma
      description: >-
        The PT-sUSDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDai-3 as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USDC
      relatedAsset: '0x6afb8d3f6d4a34e9cb2f217317f4dc8e05aa673b'
      integrationUrl: >-
        https://app.euler.finance/positions/0x5f7f81fb9a3cfbf35633349990bbc5001f365408/0x6afb8d3f6d4a34e9cb2f217317f4dc8e05aa673b?network=arbitrumone
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in an Euler
        market with eUSDC-2 as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USD₮0
      relatedAsset: '0x482c3e2530fac8fe2c63ae007ad2695c6d685e98'
      integrationUrl: >-
        https://app.euler.finance/positions/0x5f7f81fb9a3cfbf35633349990bbc5001f365408/0x482c3e2530fac8fe2c63ae007ad2695c6d685e98?network=arbitrumone
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in an Euler
        market with eUSD₮0-2 as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USDe
      relatedAsset: '0x683b777a393ba94f3c903fba2b14a6b6ff80dbe7'
      integrationUrl: >-
        https://app.euler.finance/positions/0x5f7f81fb9a3cfbf35633349990bbc5001f365408/0x683b777a393ba94f3c903fba2b14a6b6ff80dbe7?network=arbitrumone
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in an Euler
        market with eUSDe-2 as the loan token.
    - chainId: 42161
      address: '0x1bf1311fcf914a69dd5805c9b06b72f80539cb3f'
      subtitle: USDC
      relatedAsset: '0x6afb8d3f6d4a34e9cb2f217317f4dc8e05aa673b'
      integrationUrl: >-
        https://app.euler.finance/positions/0x878e12c1a1bbdf7645e28a8e9c420ccd595204ad/0x6afb8d3f6d4a34e9cb2f217317f4dc8e05aa673b?network=arbitrumone
      description: >-
        The PT-sUSDai-19FEB2026 is the asset used as collateral in an Euler
        market with eUSDC-2 as the loan token.
    - chainId: 42161
      address: '0x1bf1311fcf914a69dd5805c9b06b72f80539cb3f'
      subtitle: USD₮0
      relatedAsset: '0x482c3e2530fac8fe2c63ae007ad2695c6d685e98'
      integrationUrl: >-
        https://app.euler.finance/positions/0x878e12c1a1bbdf7645e28a8e9c420ccd595204ad/0x482c3e2530fac8fe2c63ae007ad2695c6d685e98?network=arbitrumone
      description: >-
        The PT-sUSDai-19FEB2026 is the asset used as collateral in an Euler
        market with eUSD₮0-2 as the loan token.
    - chainId: 42161
      address: '0x1bf1311fcf914a69dd5805c9b06b72f80539cb3f'
      subtitle: USDe
      relatedAsset: '0x683b777a393ba94f3c903fba2b14a6b6ff80dbe7'
      integrationUrl: >-
        https://app.euler.finance/positions/0x878e12c1a1bbdf7645e28a8e9c420ccd595204ad/0x683b777a393ba94f3c903fba2b14a6b6ff80dbe7?network=arbitrumone
      description: >-
        The PT-sUSDai-19FEB2026 is the asset used as collateral in an Euler
        market with eUSDe-2 as the loan token.
    - chainId: 42161
      address: '0x9b3924f9652cabf3db48b7b4c92e474c571b3ab4'
      subtitle: thBILL
      relatedAsset: '0x79e1f4a1cde92568d58eb823f81d9c0c7c384e6b'
      integrationUrl: >-
        https://app.euler.finance/positions/0x1da09605fefd09312b3004212a7274d7bb1dd891/0x79e1f4a1cde92568d58eb823f81d9c0c7c384e6b?network=arbitrumone
      description: >-
        The PT-thBILL-19FEB2026 is the asset used as collateral in an Euler
        market with ethBILL-2 as the loan token.
    - chainId: 42161
      address: '0x9b3924f9652cabf3db48b7b4c92e474c571b3ab4'
      subtitle: USDC
      relatedAsset: '0x44c10da836d2abe881b77bbb0b3dce5f85c0c1cc'
      integrationUrl: >-
        https://app.euler.finance/positions/0x1da09605fefd09312b3004212a7274d7bb1dd891/0x44c10da836d2abe881b77bbb0b3dce5f85c0c1cc?network=arbitrumone
      description: >-
        The PT-thBILL-19FEB2026 is the asset used as collateral in an Euler
        market with eUSDC-6 as the loan token.
    - chainId: 42161
      address: '0x9b3924f9652cabf3db48b7b4c92e474c571b3ab4'
      subtitle: USD₮0
      relatedAsset: '0xee074ceb44ada094391b9c71a7fb8ba6962d492c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x1da09605fefd09312b3004212a7274d7bb1dd891/0xee074ceb44ada094391b9c71a7fb8ba6962d492c?network=arbitrumone
      description: >-
        The PT-thBILL-19FEB2026 is the asset used as collateral in an Euler
        market with eUSD₮0-5 as the loan token.
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0xc532db16bc0530ed4920aa84ee6f84bcf8f83ef0/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-sUSDE-5FEB2026 is the asset used as collateral in an Euler market
        with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0x3de93dec4d41ffe849f7ba75041a38f7ee843bf3/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-USDe-5FEB2026 is the asset used as collateral in an Euler market
        with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0x67aeeed39c1675e0df93ad8bab543b17992d433b'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0x50e2d08603db772ebc751b2d84f58d670976298d/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-cUSDO-28MAY2026 is the asset used as collateral in an Euler
        market with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0x67aeeed39c1675e0df93ad8bab543b17992d433b'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x50e2d08603db772ebc751b2d84f58d670976298d/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-cUSDO-28MAY2026 is the asset used as collateral in an Euler
        market with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0xc532db16bc0530ed4920aa84ee6f84bcf8f83ef0/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-sUSDE-5FEB2026 is the asset used as collateral in an Euler market
        with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x3de93dec4d41ffe849f7ba75041a38f7ee843bf3/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-USDe-5FEB2026 is the asset used as collateral in an Euler market
        with efrxUSD-1 as the loan token.
    - chainId: 9745
      address: '0xedac81b27790e0728f54dea3b7718e5437e85353'
      subtitle: USDT0
      relatedAsset: '0x8aec278c2fd4cc07b10a8865aed33775f93eace6'
      integrationUrl: >-
        https://app.euler.finance/positions/0x527295f09ff7c411b213b29a0de8c816a669b3fe/0x8aec278c2fd4cc07b10a8865aed33775f93eace6?network=plasma
      description: >-
        The PT-sUSDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDT0-20 as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0x4f4afcdd8e418f5aa9130ba53af23cb7bf47f467/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in an Euler
        market with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x4f4afcdd8e418f5aa9130ba53af23cb7bf47f467/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in an Euler
        market with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0x2da35f6e88eaba4e705bff7154b259859c353953/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in an Euler
        market with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x2da35f6e88eaba4e705bff7154b259859c353953/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in an Euler
        market with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0x67aeeed39c1675e0df93ad8bab543b17992d433b'
      subtitle: USDT
      relatedAsset: '0x7c280dbdef569e96c7919251bd2b0edf0734c5a8'
      integrationUrl: >-
        https://app.euler.finance/positions/0x50e2d08603db772ebc751b2d84f58d670976298d/0x7c280dbdef569e96c7919251bd2b0edf0734c5a8?network=ethereum
      description: >-
        The PT-cUSDO-28MAY2026 is the asset used as collateral in an Euler
        market with eUSDT-9 as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDT
      relatedAsset: '0x7c280dbdef569e96c7919251bd2b0edf0734c5a8'
      integrationUrl: >-
        https://app.euler.finance/positions/0x4f4afcdd8e418f5aa9130ba53af23cb7bf47f467/0x7c280dbdef569e96c7919251bd2b0edf0734c5a8?network=ethereum
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in an Euler
        market with eUSDT-9 as the loan token.
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: USDT
      relatedAsset: '0x7c280dbdef569e96c7919251bd2b0edf0734c5a8'
      integrationUrl: >-
        https://app.euler.finance/positions/0xc532db16bc0530ed4920aa84ee6f84bcf8f83ef0/0x7c280dbdef569e96c7919251bd2b0edf0734c5a8?network=ethereum
      description: >-
        The PT-sUSDE-5FEB2026 is the asset used as collateral in an Euler market
        with eUSDT-9 as the loan token.
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: USDT
      relatedAsset: '0x7c280dbdef569e96c7919251bd2b0edf0734c5a8'
      integrationUrl: >-
        https://app.euler.finance/positions/0x3de93dec4d41ffe849f7ba75041a38f7ee843bf3/0x7c280dbdef569e96c7919251bd2b0edf0734c5a8?network=ethereum
      description: >-
        The PT-USDe-5FEB2026 is the asset used as collateral in an Euler market
        with eUSDT-9 as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDT
      relatedAsset: '0x7c280dbdef569e96c7919251bd2b0edf0734c5a8'
      integrationUrl: >-
        https://app.euler.finance/positions/0x2da35f6e88eaba4e705bff7154b259859c353953/0x7c280dbdef569e96c7919251bd2b0edf0734c5a8?network=ethereum
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in an Euler
        market with eUSDT-9 as the loan token.
  sy: []
  lp: []
