name: Euler
icon: logo.png
category: Money Market
url: https://app.euler.finance/borrow?network=ethereum
description: >-
  Euler is a modular lending platform that enables users to lend, borrow and
  build without limits.
metadata:
  pt:
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      subtitle: hgETH
      relatedAsset: '0x3f714090f7648139043349f599a48904187d76d0'
      integrationUrl: >-
        https://app.euler.finance/positions/0x18337806b02b02099209b05589e6db85acd4345c/0x3f714090f7648139043349f599a48904187d76d0?network=ethereum
      description: >-
        The PT-hgETH-25JUN2026 is the asset used as collateral in an Euler
        market with ehgETH-2 as the loan token.
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      subtitle: WETH
      relatedAsset: '0x87c414825ab3d1e9bdc773e9b1fd968822c9cf51'
      integrationUrl: >-
        https://app.euler.finance/positions/0x18337806b02b02099209b05589e6db85acd4345c/0x87c414825ab3d1e9bdc773e9b1fd968822c9cf51?network=ethereum
      description: >-
        The PT-hgETH-25JUN2026 is the asset used as collateral in an Euler
        market with eWETH-29 as the loan token.
    - chainId: 8453
      address: '0x0177055f7429d3bd6b19f2dd591127db871a510e'
      subtitle: USDC
      relatedAsset: '0x085178078796da17b191f9081b5e2fccc79a7ee7'
      integrationUrl: >-
        https://app.euler.finance/positions/0x24d633664aea3f551b2fa34fa66dd1ba52a33933/0x085178078796da17b191f9081b5e2fccc79a7ee7?network=base
      description: >-
        The PT-yoUSD-26MAR2026 is the asset used as collateral in an Euler
        market with eUSDC-29 as the loan token.
    - chainId: 8453
      address: '0x0177055f7429d3bd6b19f2dd591127db871a510e'
      subtitle: yoUSD
      relatedAsset: '0x990d616ca6e7192625d1b7c41fb67b5758df7cf2'
      integrationUrl: >-
        https://app.euler.finance/positions/0x24d633664aea3f551b2fa34fa66dd1ba52a33933/0x990d616ca6e7192625d1b7c41fb67b5758df7cf2?network=base
      description: >-
        The PT-yoUSD-26MAR2026 is the asset used as collateral in an Euler
        market with eyoUSD-1 as the loan token.
    - chainId: 8453
      address: '0x1a5c5ea50717a2ea0e4f7036fb289349deaab58b'
      subtitle: WETH
      relatedAsset: '0x774c08f8e78c47046d325c0331788954c35df10a'
      integrationUrl: >-
        https://app.euler.finance/positions/0x38df63f1986b80578b7357bcda3d4f71f129afff/0x774c08f8e78c47046d325c0331788954c35df10a?network=base
      description: >-
        The PT-yoETH-26MAR2026 is the asset used as collateral in an Euler
        market with eWETH-19 as the loan token.
    - chainId: 8453
      address: '0x1a5c5ea50717a2ea0e4f7036fb289349deaab58b'
      subtitle: yoETH
      relatedAsset: '0xdbdc9c3edbd401109c83b333c16a0251806b3330'
      integrationUrl: >-
        https://app.euler.finance/positions/0x38df63f1986b80578b7357bcda3d4f71f129afff/0xdbdc9c3edbd401109c83b333c16a0251806b3330?network=base
      description: >-
        The PT-yoETH-26MAR2026 is the asset used as collateral in an Euler
        market with eyoETH-1 as the loan token.
    - chainId: 9745
      address: '0xd516188daf64efa04a8d60872f891f2cc811a561'
      subtitle: USDai
      relatedAsset: '0x8539f99dbc4f437c1f71de6920369b9cd46193ff'
      integrationUrl: >-
        https://app.euler.finance/positions/0x5dcce5f1eddf4c1ada8bcf2da89d4bc7fb9dd5d2/0x8539f99dbc4f437c1f71de6920369b9cd46193ff?network=plasma
      description: >-
        The PT-USDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDai-2 as the loan token.
    - chainId: 9745
      address: '0xd516188daf64efa04a8d60872f891f2cc811a561'
      subtitle: USDT0
      relatedAsset: '0x98d6863fa1c247d529c94e53f521897ae9a6ebf0'
      integrationUrl: >-
        https://app.euler.finance/positions/0x5dcce5f1eddf4c1ada8bcf2da89d4bc7fb9dd5d2/0x98d6863fa1c247d529c94e53f521897ae9a6ebf0?network=plasma
      description: >-
        The PT-USDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDT0-17 as the loan token.
    - chainId: 9745
      address: '0xedac81b27790e0728f54dea3b7718e5437e85353'
      subtitle: USDT0
      relatedAsset: '0x66ab62571ccd31d911eeefea85944895e30c0a3a'
      integrationUrl: >-
        https://app.euler.finance/positions/0xce7120c69a77e90615a9d65c581fdac1fd311cdc/0x66ab62571ccd31d911eeefea85944895e30c0a3a?network=plasma
      description: >-
        The PT-sUSDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDT0-18 as the loan token.
    - chainId: 9745
      address: '0xedac81b27790e0728f54dea3b7718e5437e85353'
      subtitle: USDai
      relatedAsset: '0x4bfcf2acc5cb79ee2a00d08edfb81efd37cc2fe5'
      integrationUrl: >-
        https://app.euler.finance/positions/0xce7120c69a77e90615a9d65c581fdac1fd311cdc/0x4bfcf2acc5cb79ee2a00d08edfb81efd37cc2fe5?network=plasma
      description: >-
        The PT-sUSDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDai-3 as the loan token.
    - chainId: 1
      address: '0x67aeeed39c1675e0df93ad8bab543b17992d433b'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0x50e2d08603db772ebc751b2d84f58d670976298d/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-cUSDO-28MAY2026 is the asset used as collateral in an Euler
        market with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0x67aeeed39c1675e0df93ad8bab543b17992d433b'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x50e2d08603db772ebc751b2d84f58d670976298d/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-cUSDO-28MAY2026 is the asset used as collateral in an Euler
        market with efrxUSD-1 as the loan token.
    - chainId: 9745
      address: '0xedac81b27790e0728f54dea3b7718e5437e85353'
      subtitle: USDT0
      relatedAsset: '0x8aec278c2fd4cc07b10a8865aed33775f93eace6'
      integrationUrl: >-
        https://app.euler.finance/positions/0x527295f09ff7c411b213b29a0de8c816a669b3fe/0x8aec278c2fd4cc07b10a8865aed33775f93eace6?network=plasma
      description: >-
        The PT-sUSDai-19MAR2026 is the asset used as collateral in an Euler
        market with eUSDT0-20 as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0x4f4afcdd8e418f5aa9130ba53af23cb7bf47f467/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in an Euler
        market with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x4f4afcdd8e418f5aa9130ba53af23cb7bf47f467/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in an Euler
        market with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0x2da35f6e88eaba4e705bff7154b259859c353953/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in an Euler
        market with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x2da35f6e88eaba4e705bff7154b259859c353953/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in an Euler
        market with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0x9dfe82d2a2419b143d99a36789c405f2d8072c1e/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in an Euler
        market with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0x9dfe82d2a2419b143d99a36789c405f2d8072c1e/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in an Euler
        market with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: frxUSD
      relatedAsset: '0x20622fcd4476fbc9d5ef36ebd371307a56d9028c'
      integrationUrl: >-
        https://app.euler.finance/positions/0xd5f9afc441ca3f72b22d0b60d53e55b966c8de64/0x20622fcd4476fbc9d5ef36ebd371307a56d9028c?network=ethereum
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in an Euler market
        with efrxUSD-1 as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDC
      relatedAsset: '0xe0a80d35bb6618cba260120b279d357978c42bce'
      integrationUrl: >-
        https://app.euler.finance/positions/0xd5f9afc441ca3f72b22d0b60d53e55b966c8de64/0xe0a80d35bb6618cba260120b279d357978c42bce?network=ethereum
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in an Euler market
        with eUSDC-22 as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDe
      relatedAsset: '0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6'
      integrationUrl: >-
        https://app.euler.finance/positions/0x4f4afcdd8e418f5aa9130ba53af23cb7bf47f467/0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6?network=ethereum
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in an Euler
        market with eUSDe-6 as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDe
      relatedAsset: '0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6'
      integrationUrl: >-
        https://app.euler.finance/positions/0x9dfe82d2a2419b143d99a36789c405f2d8072c1e/0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6?network=ethereum
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in an Euler
        market with eUSDe-6 as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDe
      relatedAsset: '0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6'
      integrationUrl: >-
        https://app.euler.finance/positions/0x2da35f6e88eaba4e705bff7154b259859c353953/0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6?network=ethereum
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in an Euler
        market with eUSDe-6 as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDe
      relatedAsset: '0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6'
      integrationUrl: >-
        https://app.euler.finance/positions/0xd5f9afc441ca3f72b22d0b60d53e55b966c8de64/0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6?network=ethereum
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in an Euler market
        with eUSDe-6 as the loan token.
    - chainId: 1
      address: '0x67aeeed39c1675e0df93ad8bab543b17992d433b'
      subtitle: USDe
      relatedAsset: '0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6'
      integrationUrl: >-
        https://app.euler.finance/positions/0x50e2d08603db772ebc751b2d84f58d670976298d/0x2daca71cb58285212dc05d65cfd4f59a82bc4cf6?network=ethereum
      description: >-
        The PT-cUSDO-28MAY2026 is the asset used as collateral in an Euler
        market with eUSDe-6 as the loan token.
  sy: []
  lp: []
