name: Silo
icon: logo.png
category: Money Market
metadata:
  pt:
  - chainId: 146
      address: '0xBe27993204Ec64238F71A527B4c4D5F4949034C3'
      integrationUrl: https://v2.silo.finance/markets/sonic/ptwstkscusd29may-frxusd-37
      description: >-
        Leverage PT-wstkscUSD against frxUSD on Silo to maximize your 
        fixed yield while earning bonus Silo Points.
    - chainId: 146
      address: '0x420df605D062F8611EFb3F203BF258159b8FfFdE'
      integrationUrl: https://v2.silo.finance/markets/sonic/ptsts29may-s-40
      description: >-
        Leverage PT-stS against S on Silo to maximize your 
        fixed yield while earning bonus Silo Points.
      - chainId: 146
      address: '0x930441Aa7Ab17654dF5663781CA0C02CC17e6643'
      integrationUrl: https://v2.silo.finance/markets/sonic/ptausdc14aug-scusd-46
      description: >-
        Leverage PT-aUSDC against scUSD on Silo to maximize your 
        fixed yield while earning bonus Silo Points.
        - chainId: 146
      address: '0xa2161E75EDf50d70544e6588788A5732A3105c00'
      integrationUrl: https://v2.silo.finance/markets/sonic/ptwstksceth29may-eth-35
      description: >-
        Leverage PT-wstkscETH against ETH on Silo to maximize your 
        fixed yield while earning bonus Silo Points.
          - chainId: 146
      address: '0xBe27993204Ec64238F71A527B4c4D5F4949034C3'
      integrationUrl: https://v2.silo.finance/markets/sonic/ptwstkscusd29may-usdc-34
      description: >-
        Leverage PT-wstkscUSD against USDC on Silo to maximize your 
        fixed yield while earning bonus Silo Points.
            - chainId: 146
      address: '0x46eb02b9F47634c4fab3110CC7ADc1C6311DfAC1'
      integrationUrl: https://v2.silo.finance/markets/sonic/ptwos29may-s-41
      description: >-
        Leverage PT-woS against S on Silo to maximize your 
        fixed yield while earning bonus Silo Points.
              - chainId: 146
      address: '0xa2161E75EDf50d70544e6588788A5732A3105c00'
      integrationUrl: https://v2.silo.finance/markets/sonic/ptwstksceth29may-sceth-47
      description: >-
        Leverage PT-wstkscETH against scETH on Silo to maximize your 
        fixed yield while earning bonus Silo Points.
                - chainId: 146
      address: '0xBe27993204Ec64238F71A527B4c4D5F4949034C3'
      integrationUrl: https://v2.silo.finance/markets/sonic/ptwstkscusd29may-scusd-44
      description: >-
        Leverage PT-wstkscUSD against scUSD on Silo to maximize your 
        fixed yield while earning bonus Silo Points.
  yt: []
  lp: []
