name: Silo
icon: logo.png
category: Money Market
url: https://app.silo.finance/
description: >-
  Silo is a high-yield, risk-isolated money markets for lending and borrowing
  any crypto assets
metadata:
  pt:
    - chainId: 146
      address: '0x200338559c1975d1f216adcda8352aff2869afab'
      integrationUrl: https://app.silo.finance/markets/sonic/106
      description: >-
        Leverage PT-wOS-18DEC2025 against S on Silo to maximize your fixed yield
        while earning bonus Silo Points.
      subtitle: S
    - chainId: 146
      address: '0x7e52f587f5b870d4c2cac8559ac4c49742d31a28'
      integrationUrl: https://app.silo.finance/markets/sonic/108
      description: >-
        Leverage PT-wstkscETH-18DEC2025 against ETH on Silo to maximize your
        fixed yield while earning bonus Silo Points.
      subtitle: ETH
    - chainId: 146
      address: '0x0fb682c9692addcc1769f4d4d938c54420d54fa3'
      integrationUrl: https://app.silo.finance/markets/sonic/105
      description: >-
        Leverage PT-wstkscUSD-18DEC2025 against USDC on Silo to maximize your
        fixed yield while earning bonus Silo Points.
      subtitle: USDC
    - chainId: 146
      address: '0xe2bc30a4896ff4c52adcb180213666d2d6b21c6d'
      integrationUrl: https://app.silo.finance/markets/sonic/113
      description: >-
        Leverage PT-stS-18DEC2025 against S on Silo to maximize your fixed yield
        while earning bonus Silo Points.
      subtitle: S
    - chainId: 146
      address: '0x0fb682c9692addcc1769f4d4d938c54420d54fa3'
      integrationUrl: https://app.silo.finance/markets/sonic/148
      description: >-
        Leverage PT-wstkscUSD-18DEC2025 against dUSD on Silo to maximize your
        fixed yield while earning bonus Silo Points.
      subtitle: dUSD
    - chainId: 43114
      address: '0x9Da7f8c0D6e3F247AFFDf92c3DDDd83c1E248E14'
      integrationUrl: https://app.silo.finance/markets/avalanche/148
      description: >-
        Leverage PT-USDe-27NOV2025 against USDC on Silo to maximize your fixed
        yield.
  yt: []
  lp: []
