name: Contango
icon: logo.png
category: Yield Strategy
url: https://app.contango.xyz/
description: >-
  Contango builds positions by automating looping strategies through flash
  loans. When a trader opens a position, the protocol borrows on money markets.
metadata:
  pt:
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      integrationUrl: >-
        https://app.contango.xyz/strategies/leveraged-staking/eth?selectedChains=1
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0x29fd7180e5cced14ad148c7997e6b6857a8be86e'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0xeeaa924eb3667f30be02db9c55d87566a3f4df7a'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
  yt: []
  lp: []
