name: Contango
icon: logo.png
category: Yield Strategy
url: https://app.contango.xyz/
description: >-
  Contango builds positions by automating looping strategies through flash
  loans. When a trader opens a position, the protocol borrows on money markets.
metadata:
  pt:
    - chainId: 1
      address: '0x5b1578e2604b91bd7b24f86f0e5ef6c024bb3a14'
      integrationUrl: >-
        https://app.contango.xyz/strategies/leveraged-staking/eth?selectedChains=1
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0x29fd7180e5cced14ad148c7997e6b6857a8be86e'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0xaebf0bb9f57e89260d57f31af34eb58657d96ce0'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
    - chainId: 1
      address: '0x3de0ff76e8b528c092d47b9dac775931cef80f49'
      integrationUrl: https://app.contango.xyz/
      description: PT leverage looping through various supported money markets
  yt: []
  lp: []
