name: Aave
icon: logo.png
category: Money Market
description: >-
  Aave is a decentralised non-custodial liquidity protocol where users can
  participate as suppliers or borrowers
url: https://app.aave.com/
metadata:
  pt:
    - chainId: 1
      address: '0xe6a934089bbee34f832060ce98848359883749b3'
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xe6a934089bbee34f832060ce98848359883749b3&marketName=proto_mainnet_v3
      description: >-
        PT-sUSDe-27NOV2025 can be used as collateral to borrow or multiply
        against a variety of assets on Aave
    - chainId: 1
      address: '0x62c6e813b9589c3631ba0cdb013acdb8544038b7'
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x62c6e813b9589c3631ba0cdb013acdb8544038b7&marketName=proto_mainnet_v3
      description: >-
        PT-USDe-27NOV2025 can be used as collateral to borrow or multiply
        against a variety of assets on Aave
    - chainId: 9745
      address: '0x93B544c330F60A2aa05ceD87aEEffB8D38FD8c9a'
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x93B544c330F60A2aa05ceD87aEEffB8D38FD8c9a&marketName=AaveV3Plasma
      description: >-
        PT-USDe-15JAN2026 can be used as collateral to borrow or multiply
        against a variety of assets on Aave
    - chainId: 9745
      address: '0x02FCC4989B4C9D435b7ceD3fE1Ba4CF77BBb5Dd8'
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x02FCC4989B4C9D435b7ceD3fE1Ba4CF77BBb5Dd8&marketName=AaveV3Plasma
      description: >-
        PT-sUSDE-15JAN2026 can be used as collateral to borrow or multiply
        against a variety of assets on Aave
  yt: []
  lp: []
