name: Aave
icon: logo.png
category: Money Market
description: >-
  Aave is a decentralised non-custodial liquidity protocol where users can
  participate as suppliers or borrowers
url: https://app.aave.com/
metadata:
  pt:
    - chainId: 9745
      address: '0x54dc267be2839303ff1e323584a16e86cec4aa44'
      subtitle: USDT0
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x54dc267be2839303ff1e323584a16e86cec4aa44&marketName=proto_plasma_v3
      description: PT-USDe-9APR2026 can be used as collateral to borrow USDT0 on Aave
    - chainId: 9745
      address: '0x54dc267be2839303ff1e323584a16e86cec4aa44'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x54dc267be2839303ff1e323584a16e86cec4aa44&marketName=proto_plasma_v3
      description: PT-USDe-9APR2026 can be used as collateral to borrow USDe on Aave
    - chainId: 9745
      address: '0xab509448ad489e2e1341e25cc500f2596464cc82'
      subtitle: USDT0
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xab509448ad489e2e1341e25cc500f2596464cc82&marketName=proto_plasma_v3
      description: PT-sUSDE-9APR2026 can be used as collateral to borrow USDT0 on Aave
    - chainId: 9745
      address: '0xab509448ad489e2e1341e25cc500f2596464cc82'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xab509448ad489e2e1341e25cc500f2596464cc82&marketName=proto_plasma_v3
      description: PT-sUSDE-9APR2026 can be used as collateral to borrow USDe on Aave
  yt: []
  lp: []
