name: Aave
icon: logo.png
category: Money Market
description: >-
  Aave is a decentralised non-custodial liquidity protocol where users can
  participate as suppliers or borrowers
url: https://app.aave.com/
metadata:
  pt:
    - chainId: 9745
      address: '0x93B544c330F60A2aa05ceD87aEEffB8D38FD8c9a'
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x93b544c330f60a2aa05ced87aeeffb8d38fd8c9a&marketName=proto_plasma_v3
      description: >-
        PT-USDe-15JAN2026 can be used as collateral to borrow or multiply
        against a variety of assets on Aave
    - chainId: 9745
      address: '0x02FCC4989B4C9D435b7ceD3fE1Ba4CF77BBb5Dd8'
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x02fcc4989b4c9d435b7ced3fe1ba4cf77bbb5dd8&marketName=proto_plasma_v3
      description: >-
        PT-sUSDE-15JAN2026 can be used as collateral to borrow or multiply
        against a variety of assets on Aave
    - chainId: 9745
      address: '0x02fcc4989b4c9d435b7ced3fe1ba4cf77bbb5dd8'
      subtitle: USDT0
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x02fcc4989b4c9d435b7ced3fe1ba4cf77bbb5dd8&marketName=proto_plasma_v3
      description: PT-sUSDE-15JAN2026 can be used as collateral to borrow USDT0 on Aave
    - chainId: 9745
      address: '0x02fcc4989b4c9d435b7ced3fe1ba4cf77bbb5dd8'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x02fcc4989b4c9d435b7ced3fe1ba4cf77bbb5dd8&marketName=proto_plasma_v3
      description: PT-sUSDE-15JAN2026 can be used as collateral to borrow USDe on Aave
    - chainId: 9745
      address: '0x93b544c330f60a2aa05ced87aeeffb8d38fd8c9a'
      subtitle: USDT0
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x93b544c330f60a2aa05ced87aeeffb8d38fd8c9a&marketName=proto_plasma_v3
      description: PT-USDe-15JAN2026 can be used as collateral to borrow USDT0 on Aave
    - chainId: 9745
      address: '0x93b544c330f60a2aa05ced87aeeffb8d38fd8c9a'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x93b544c330f60a2aa05ced87aeeffb8d38fd8c9a&marketName=proto_plasma_v3
      description: PT-USDe-15JAN2026 can be used as collateral to borrow USDe on Aave
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: USDT
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x1f84a51296691320478c98b8d77f2bbd17d34350&marketName=proto_ethereum_v3
      description: PT-USDe-5FEB2026 can be used as collateral to borrow USDT on Aave
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: USDC
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x1f84a51296691320478c98b8d77f2bbd17d34350&marketName=proto_ethereum_v3
      description: PT-USDe-5FEB2026 can be used as collateral to borrow USDC on Aave
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x1f84a51296691320478c98b8d77f2bbd17d34350&marketName=proto_ethereum_v3
      description: PT-USDe-5FEB2026 can be used as collateral to borrow USDe on Aave
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: USDtb
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0x1f84a51296691320478c98b8d77f2bbd17d34350&marketName=proto_ethereum_v3
      description: PT-USDe-5FEB2026 can be used as collateral to borrow USDtb on Aave
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: USDT
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xe8483517077afa11a9b07f849cee2552f040d7b2&marketName=proto_ethereum_v3
      description: PT-sUSDE-5FEB2026 can be used as collateral to borrow USDT on Aave
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xe8483517077afa11a9b07f849cee2552f040d7b2&marketName=proto_ethereum_v3
      description: PT-sUSDE-5FEB2026 can be used as collateral to borrow USDC on Aave
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: USDe
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xe8483517077afa11a9b07f849cee2552f040d7b2&marketName=proto_ethereum_v3
      description: PT-sUSDE-5FEB2026 can be used as collateral to borrow USDe on Aave
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: USDtb
      integrationUrl: >-
        https://app.aave.com/reserve-overview/?underlyingAsset=0xe8483517077afa11a9b07f849cee2552f040d7b2&marketName=proto_ethereum_v3
      description: PT-sUSDE-5FEB2026 can be used as collateral to borrow USDtb on Aave
  yt: []
  lp: []
