name: Morpho
icon: logo.png
category: Money Market
url: https://app.morpho.org/ethereum/borrow
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 1
      address: '0x3eaa0f0f0a5d3d595ae4e4b0d27f439d01c3e7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x9bc98c2f20ac58287ef2c860eea53a2fdc27c17a7817ff1206c0b7840cc7cd79&network=mainnet
      description: >-
        The PT-reUSD-25JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x29fd7180e5cced14ad148c7997e6b6857a8be86e'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x1cfdc0154ae6b9f1887a8250f2582d55606e1a2008e65108fb83dd50a928593e&network=mainnet
      description: >-
        The PT-RLP-9APR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0x5413b86d5c0a2950aedcbdb6b5074a63e92fda3375f76d0eeea0f359605508f7&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 130
      address: '0xb6168f597cd37a232cb7cb94cd1786be20ead156'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xe79e0d1f753be4cfb44b04d790d4f66d6b5ca34aa3b83d51f69f1ce50b98dd8e&network=unichain
      description: >-
        The PT-cUSD-29JAN2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x0fe4a1bbe013b54e38ef4e4ec8ba1d64d12a0663'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x8f31bcd38b1046e6a8d61a828cb37c55825b410bb2daf1a2296b089925133064&network=unichain
      description: >-
        The PT-USDai-19FEB2026-(ARB) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x54bf2659b5cdfd86b75920e93c0844c0364f5166'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2a9a5c436719badcfadbad3ad8e8179a160ded758603eaa03a883f922a1790d3&network=mainnet
      description: >-
        The PT-sNUSD-5MAR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x27b9a0a5bfee98a31eb51e3850250d103a9f8e41673c782defc66aa943af0e65&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb2f87218f0e2478ba7a2b8be9fe76cbd6f54f8654b9651d4bd1f0ea536674691&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0xba8c21d3e47814574a61bee82e7053274f731ad253b24865acab8476fa477ee7&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 1
      address: '0xaf76b3af3477e4a2cd0b7f80c3152108c19a25e5'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xaac3ffcdf8a75919657e789fa72ab742a7bbfdf5bb0b87e4bbeb3c29bbbbb05c&network=mainnet
      description: >-
        The PT-siUSD-26MAR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2afd063a5af8e050069cfad4da95c81768b85b140bea2bd89e00407b15ce82c8&network=mainnet
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xeeaa924eb3667f30be02db9c55d87566a3f4df7a'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb82cb1140daae367c1f39dd6b4ec6a3aaef997764c84634ad8a4114571c15ef3&network=mainnet
      description: >-
        The PT-RUSD-26FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x64b393288ab2a0fe7af6b73a9159493e60ab0605'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x3d353ef0436b85c3b12d53536c19b21c533c046b07c9d92d791a1510e7ef0b74&network=mainnet
      description: >-
        The PT-mAPOLLO-30APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd87169640666649f1e6f92034dca9e4ae748de69'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xca432a8b0f33541cfe164d388823d05b607db43b690d4856f343eec3b42402c0&network=mainnet
      description: >-
        The PT-mHYPER-30APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xcf30228b60d9ec544889f5a77a2fada8e8d19ab921e0d7d35c7d011b54ade4d0&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xf982e67987ed310641bb33f1e7ebf3a0a2930f6b00d8f6b089440ace18f76c9b&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xeeaa924eb3667f30be02db9c55d87566a3f4df7a'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xdeca5331fa55b630026fedf5b2bfa0d384b35dbebd9921832e67ad305f48d8d8&network=mainnet
      description: >-
        The PT-RUSD-26FEB2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 130
      address: '0x9d9874e867b877dd0a3f1eafb8bb1bc54eecc682'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x87a686cc100aabe917f8e1ad58140a1b63f0edbb9650a32c0526718dc610b2d5&network=unichain
      description: >-
        The PT-cUSD-23JUL2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x026644dc6fc4cf22a45ad14231090c7736d07507'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x54ea85acf999d0229f0bde475e43674972c4261972a6d78ba34e659bbabe947a&network=unichain
      description: >-
        The PT-srUSDe-2APR2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x702b7ec7628de2622e51e1bb34a7e6ad9e95f3a25a2ed361e4ce621f23f5e642&network=mainnet
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xfd039edc69eac5eaab4a10463fdbcaca75d6eddb1f0e00248d73fc977fb2554b&network=mainnet
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0xe7f998c0ff11ca2bf091d39b6a3cef1035733528187d520c1c47710c8f1acaeb&network=mainnet
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with AUSD as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2fb3713487c7812e7309935b034f40228841666f6b048faf31fd2110ae674f20&network=mainnet
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0x5eaaebc81e9e27972ab458811d1b60828e8ab51ef6620f9b3918fd7e68eecec1&network=mainnet
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0x54e42432a7c0309ba650080cab6fcff377034fd9de174bbd3a4b519186ffc0f8&network=mainnet
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 1
      address: '0x606b5c773dc4d6e625c411cf60565f8c30c467d2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xc978f01522ff64adafd91856065d602c56e326a0368b895bd9244d5998e60076&network=mainnet
      description: >-
        The PT-savUSD-14MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
  yt: []
  lp: []
