name: Morpho
icon: logo.png
category: Money Market
url: https://app.morpho.org/ethereum/borrow
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 42161
      address: '0x1bf1311fcf914a69dd5805c9b06b72f80539cb3f'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x7717f1e04510390518811b3133ea47c298094ddd1d806ed8f8867d88c727bad7&network=arbitrum
      description: >-
        The PT-sUSDai-19FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x9b3924f9652cabf3db48b7b4c92e474c571b3ab4'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x6c831dcc45a7c0af00b751da651bd874b96653c587615d11aafade7b357c4b43&network=arbitrum
      description: >-
        The PT-thBILL-19FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xec4402d1389e749c14a7caeef3e4c1f861e09bc8'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb4b257c2b8001847d361a55fcd30a7bd630750bf492b85b37c4646e42e8e0d8c&network=mainnet
      description: >-
        The PT-iUSD-19FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x3eaa0f0f0a5d3d595ae4e4b0d27f439d01c3e7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x9bc98c2f20ac58287ef2c860eea53a2fdc27c17a7817ff1206c0b7840cc7cd79&network=mainnet
      description: >-
        The PT-reUSD-25JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x29fd7180e5cced14ad148c7997e6b6857a8be86e'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x1cfdc0154ae6b9f1887a8250f2582d55606e1a2008e65108fb83dd50a928593e&network=mainnet
      description: >-
        The PT-RLP-9APR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0x5413b86d5c0a2950aedcbdb6b5074a63e92fda3375f76d0eeea0f359605508f7&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 130
      address: '0xb6168f597cd37a232cb7cb94cd1786be20ead156'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xe79e0d1f753be4cfb44b04d790d4f66d6b5ca34aa3b83d51f69f1ce50b98dd8e&network=unichain
      description: >-
        The PT-cUSD-29JAN2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x0fe4a1bbe013b54e38ef4e4ec8ba1d64d12a0663'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x8f31bcd38b1046e6a8d61a828cb37c55825b410bb2daf1a2296b089925133064&network=unichain
      description: >-
        The PT-USDai-19FEB2026-(ARB) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x8147c63f3f6f5a0825c84bf2cb11443c72b609fa39cf9a362e3d4dc2c5ca76c4&network=arbitrum
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USDT0
      integrationUrl: >-
        https://app.morpho.org/market?id=0x090ff0cd57a258b342c870691a180bb79691e97b31ddda2b7cdd4b5a362c3cca&network=arbitrum
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in a Morpho
        market with USDT0 as the loan token.
    - chainId: 1
      address: '0x54bf2659b5cdfd86b75920e93c0844c0364f5166'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2a9a5c436719badcfadbad3ad8e8179a160ded758603eaa03a883f922a1790d3&network=mainnet
      description: >-
        The PT-sNUSD-5MAR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x27b9a0a5bfee98a31eb51e3850250d103a9f8e41673c782defc66aa943af0e65&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb2f87218f0e2478ba7a2b8be9fe76cbd6f54f8654b9651d4bd1f0ea536674691&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0xba8c21d3e47814574a61bee82e7053274f731ad253b24865acab8476fa477ee7&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 1
      address: '0xaf76b3af3477e4a2cd0b7f80c3152108c19a25e5'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xaac3ffcdf8a75919657e789fa72ab742a7bbfdf5bb0b87e4bbeb3c29bbbbb05c&network=mainnet
      description: >-
        The PT-siUSD-26MAR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2afd063a5af8e050069cfad4da95c81768b85b140bea2bd89e00407b15ce82c8&network=mainnet
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xd174bb7b8dd6ef16b116753b56679932ee13382b94f81bf66a2b37962cb41f56&network=mainnet
      description: >-
        The PT-sUSDE-5FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0xeeaa924eb3667f30be02db9c55d87566a3f4df7a'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb82cb1140daae367c1f39dd6b4ec6a3aaef997764c84634ad8a4114571c15ef3&network=mainnet
      description: >-
        The PT-RUSD-26FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x64b393288ab2a0fe7af6b73a9159493e60ab0605'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x3d353ef0436b85c3b12d53536c19b21c533c046b07c9d92d791a1510e7ef0b74&network=mainnet
      description: >-
        The PT-mAPOLLO-30APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd87169640666649f1e6f92034dca9e4ae748de69'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xca432a8b0f33541cfe164d388823d05b607db43b690d4856f343eec3b42402c0&network=mainnet
      description: >-
        The PT-mHYPER-30APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xcf30228b60d9ec544889f5a77a2fada8e8d19ab921e0d7d35c7d011b54ade4d0&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xf982e67987ed310641bb33f1e7ebf3a0a2930f6b00d8f6b089440ace18f76c9b&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xeeaa924eb3667f30be02db9c55d87566a3f4df7a'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xdeca5331fa55b630026fedf5b2bfa0d384b35dbebd9921832e67ad305f48d8d8&network=mainnet
      description: >-
        The PT-RUSD-26FEB2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 130
      address: '0x9d9874e867b877dd0a3f1eafb8bb1bc54eecc682'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x87a686cc100aabe917f8e1ad58140a1b63f0edbb9650a32c0526718dc610b2d5&network=unichain
      description: >-
        The PT-cUSD-23JUL2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x7d4799e15dcaad9da49ab8edf46d647db2da2ff419db52e8ec0984d0c49e8b9b&network=arbitrum
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x026644dc6fc4cf22a45ad14231090c7736d07507'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x54ea85acf999d0229f0bde475e43674972c4261972a6d78ba34e659bbabe947a&network=unichain
      description: >-
        The PT-srUSDe-2APR2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x32a8b98a4c4b9f3b56798e6a7593799f5e1c33108302eacf981efa108fc4b131&network=mainnet
      description: >-
        The PT-USDe-5FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x702b7ec7628de2622e51e1bb34a7e6ad9e95f3a25a2ed361e4ce621f23f5e642&network=mainnet
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xfd039edc69eac5eaab4a10463fdbcaca75d6eddb1f0e00248d73fc977fb2554b&network=mainnet
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0xe7f998c0ff11ca2bf091d39b6a3cef1035733528187d520c1c47710c8f1acaeb&network=mainnet
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with AUSD as the loan token.
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: PYUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0x5c4120f5129199ac747086fe3d141e6fe904ea335a7b9aa4059d065603afcefc&network=mainnet
      description: >-
        The PT-sUSDE-5FEB2026 is the asset used as collateral in a Morpho market
        with PYUSD as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2fb3713487c7812e7309935b034f40228841666f6b048faf31fd2110ae674f20&network=mainnet
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
  yt: []
  lp: []
