name: Morpho
icon: logo.png
category: Money Market
url: https://app.morpho.org/ethereum/borrow
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 1
      address: '0xb10da2f9147f9cf2b8826877cd0c95c18a0f42dc'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x8a71a66ac828c2b6d4f8accce5859aba0822b502f3833bec4aff09479affffdb&network=mainnet
      description: >-
        The PT-cUSDO-20NOV2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xe4d30ccf87cb3e5e637b64a2ee21bd5d3901839a'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x1ca75949a91c157183f53282d73c37191e7cd84002310f6632047d874aad4a0f&network=mainnet
      description: >-
        The PT-mHYPER-20NOV2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xc3c7e5e277d31cd24a3ac4cc9af3b6770f30ea33'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x03f715ef1ae508ab3e1faf4dffdbf2a077d1f0ad10c5aad42cf4438d5e3328af&network=mainnet
      description: >-
        The PT-stcUSD-29JAN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x545a490f9ab534adf409a2e682bc4098f49952e3'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x802ec6e878dc9fe6905b8a0a18962dcca10440a87fa2242fbf4a0461c7b0c789&network=mainnet
      description: >-
        The PT-cUSD-29JAN2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 42161
      address: '0x936f210d277bf489a3211cef9ab4bc47a7b69c96'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x58df3ad9cf719b1ca97365db634a11b770785517f409ecbe85eefdb34803de1f&network=arbitrum
      description: >-
        The PT-sUSDai-20NOV2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x8b4ca42bb3b1d789859f106222cf7dc5eed48ccb'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xf4ab212f6fcc943e2669cb6307fa4b608b0418ac5255c100e58394822157785c&network=arbitrum
      description: >-
        The PT-USDai-20NOV2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xcb95d32b87d2eceb196af2152147de371af3c7c9'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xf5de1cd86d1b96dae889356d9515a1ccfd6caae8570f8d6d49c218bb203d045d&network=mainnet
      description: >-
        The PT-reUSD-18DEC2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xe6a934089bbee34f832060ce98848359883749b3'
      subtitle: USDS
      integrationUrl: >-
        https://app.morpho.org/market?id=0xa79d8028dec527565028fd9fc075b02b498f2b69a1d519dff543ba99b812ff6b&network=mainnet
      description: >-
        The PT-sUSDE-27NOV2025 is the asset used as collateral in a Morpho
        market with USDS as the loan token.
    - chainId: 1
      address: '0x1fb3c5c35d95f48e48ffc8e36bcce5cb5f29f57c'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x79b4e55cef9e7c214b5cc965e1984229ada26a66051e35366a75c4d92b776735&network=mainnet
      description: >-
        The PT-srUSDe-15JAN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd2e230f71ca8db211067bc4070a94d268b313fa3'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x33778d3d3bfe5a6e2678e2aeecca65b819b594b3f646b6cdb0a245bbbbcb3a7f&network=mainnet
      description: >-
        The PT-alUSD-11DEC2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x5a791652f3b140d357df072d355a98ab754877d1'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x30c505b1ce479157e1035bdc5de3d4c811cf3e427c31db0b81b5c27a09054e97&network=arbitrum
      description: >-
        The PT-thBILL-27NOV2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xe6a934089bbee34f832060ce98848359883749b3'
      subtitle: USDtb
      integrationUrl: >-
        https://app.morpho.org/market?id=0x7643c3cacfeecb46249e9a2caf2a0e2f2ffeff9e9d46d20b42c9f30cfd5afeac&network=mainnet
      description: >-
        The PT-sUSDE-27NOV2025 is the asset used as collateral in a Morpho
        market with USDtb as the loan token.
  yt: []
  lp:
    - chainId: 1
      address: '0x4339ffe2b7592dc783ed13cce310531ab366deac'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xfd2e0d55ed4fcc26fec66f2bb890a8eeb985e456ac236b29127c75db3e1e23c8/lp-susde-31jul2025-usdt
      description: >-
        The LP-sUSDe-31JUL2025 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0xa36b60a14a1a5247912584768c6e53e1a269a9f7'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x134c6d598a8314a53b15d5fa5005f8bb16ba97dee6350d4a317d09b7af4dab6f/lp-susde-25sep2025-usdt
      description: >-
        The LP-sUSDe-25SEP2025 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0xe93b4a93e80bd3065b290394264af5d82422ee70'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xfc238b7b39e0febab89433ab0380f2988b13671c1884d7ebb2f3eba4627261f0/lp-eusde-14aug2025-usdt
      description: >-
        The LP-eUSDe-14AUG2025 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
