name: Morpho
icon: logo.png
category: Money Market
url: https://app.morpho.org/ethereum/borrow
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 1
      address: '0xc3c7e5e277d31cd24a3ac4cc9af3b6770f30ea33'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x03f715ef1ae508ab3e1faf4dffdbf2a077d1f0ad10c5aad42cf4438d5e3328af&network=mainnet
      description: >-
        The PT-stcUSD-29JAN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x545a490f9ab534adf409a2e682bc4098f49952e3'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x802ec6e878dc9fe6905b8a0a18962dcca10440a87fa2242fbf4a0461c7b0c789&network=mainnet
      description: >-
        The PT-cUSD-29JAN2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x9079e3af3ee265c8c49a75670db2a02bbfb8e822'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xfa5b0b24e68c993c1df02bcd6c1c774a9d3e4b311967d94ad1f2d0fee8f82a86&network=mainnet
      description: >-
        The PT-mHYPER-29JAN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x1bf1311fcf914a69dd5805c9b06b72f80539cb3f'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x7717f1e04510390518811b3133ea47c298094ddd1d806ed8f8867d88c727bad7&network=arbitrum
      description: >-
        The PT-sUSDai-19FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x9b3924f9652cabf3db48b7b4c92e474c571b3ab4'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x6c831dcc45a7c0af00b751da651bd874b96653c587615d11aafade7b357c4b43&network=arbitrum
      description: >-
        The PT-thBILL-19FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x1f84a51296691320478c98b8d77f2bbd17d34350'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x32a8b98a4c4b9f3b56798e6a7593799f5e1c33108302eacf981efa108fc4b131&network=mainnet
      description: >-
        The PT-USDe-5FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0xec4402d1389e749c14a7caeef3e4c1f861e09bc8'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb4b257c2b8001847d361a55fcd30a7bd630750bf492b85b37c4646e42e8e0d8c&network=mainnet
      description: >-
        The PT-iUSD-19FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x97ca796aed60a4e34a7d7878f399b51e8718fbf7'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x40c87599919c5af2427d6c75fa5dd3ca98feb041d9d06a7b24c8076d300f7dab&network=mainnet
      description: >-
        The PT-DUSD-29JAN2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x3eaa0f0f0a5d3d595ae4e4b0d27f439d01c3e7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x9bc98c2f20ac58287ef2c860eea53a2fdc27c17a7817ff1206c0b7840cc7cd79&network=mainnet
      description: >-
        The PT-reUSD-25JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x29fd7180e5cced14ad148c7997e6b6857a8be86e'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x1cfdc0154ae6b9f1887a8250f2582d55606e1a2008e65108fb83dd50a928593e&network=mainnet
      description: >-
        The PT-RLP-9APR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0x5413b86d5c0a2950aedcbdb6b5074a63e92fda3375f76d0eeea0f359605508f7&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 130
      address: '0xb6168f597cd37a232cb7cb94cd1786be20ead156'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xe79e0d1f753be4cfb44b04d790d4f66d6b5ca34aa3b83d51f69f1ce50b98dd8e&network=unichain
      description: >-
        The PT-cUSD-29JAN2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x0fe4a1bbe013b54e38ef4e4ec8ba1d64d12a0663'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x8f31bcd38b1046e6a8d61a828cb37c55825b410bb2daf1a2296b089925133064&network=unichain
      description: >-
        The PT-USDai-19FEB2026-(ARB) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x8147c63f3f6f5a0825c84bf2cb11443c72b609fa39cf9a362e3d4dc2c5ca76c4&network=arbitrum
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x1ef58a7af39883cc95c59a2c106b726c64c2ecc6'
      subtitle: USDT0
      integrationUrl: >-
        https://app.morpho.org/market?id=0xff608e5881ccba3859006b3c01e377314384c3d661d684c3e8b6354146e62155&network=arbitrum
      description: >-
        The PT-syrupUSDC-29JAN2026 is the asset used as collateral in a Morpho
        market with USDT0 as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USDT0
      integrationUrl: >-
        https://app.morpho.org/market?id=0x090ff0cd57a258b342c870691a180bb79691e97b31ddda2b7cdd4b5a362c3cca&network=arbitrum
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in a Morpho
        market with USDT0 as the loan token.
    - chainId: 1
      address: '0x54bf2659b5cdfd86b75920e93c0844c0364f5166'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2a9a5c436719badcfadbad3ad8e8179a160ded758603eaa03a883f922a1790d3&network=mainnet
      description: >-
        The PT-sNUSD-5MAR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x545a490f9ab534adf409a2e682bc4098f49952e3'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0x335e8e8f1324b1e43e16c5101f4db793fed10a6e63340bc4b3ad38106559e9d9&network=mainnet
      description: >-
        The PT-cUSD-29JAN2026 is the asset used as collateral in a Morpho market
        with AUSD as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x27b9a0a5bfee98a31eb51e3850250d103a9f8e41673c782defc66aa943af0e65&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb2f87218f0e2478ba7a2b8be9fe76cbd6f54f8654b9651d4bd1f0ea536674691&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0xba8c21d3e47814574a61bee82e7053274f731ad253b24865acab8476fa477ee7&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 1
      address: '0xaf76b3af3477e4a2cd0b7f80c3152108c19a25e5'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xaac3ffcdf8a75919657e789fa72ab742a7bbfdf5bb0b87e4bbeb3c29bbbbb05c&network=mainnet
      description: >-
        The PT-siUSD-26MAR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xc3c7e5e277d31cd24a3ac4cc9af3b6770f30ea33'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0x3845819ef4d8ad934bdb923d7112653adfa9efa19acffeafc3ff75043d301231&network=mainnet
      description: >-
        The PT-stcUSD-29JAN2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2afd063a5af8e050069cfad4da95c81768b85b140bea2bd89e00407b15ce82c8&network=mainnet
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xc3c7e5e277d31cd24a3ac4cc9af3b6770f30ea33'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0x226966874fecfb817a431ffb7458d0acb082579eb99b448e9ec98d9249e06341&network=mainnet
      description: >-
        The PT-stcUSD-29JAN2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 42161
      address: '0x1ef58a7af39883cc95c59a2c106b726c64c2ecc6'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x84367e5bc5df26437618f749d5beb793746e620560721fec15518d684191ebc6&network=arbitrum
      description: >-
        The PT-syrupUSDC-29JAN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x5b2c615e22272234aacf187632a0531ca1243279'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x7d4799e15dcaad9da49ab8edf46d647db2da2ff419db52e8ec0984d0c49e8b9b&network=arbitrum
      description: >-
        The PT-USDai-19FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: PYUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0x5c4120f5129199ac747086fe3d141e6fe904ea335a7b9aa4059d065603afcefc&network=mainnet
      description: >-
        The PT-sUSDE-5FEB2026 is the asset used as collateral in a Morpho market
        with PYUSD as the loan token.
    - chainId: 1
      address: '0xfceeb7586bab730fa400a5bf3fcf298d0db4c7e7'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xaaef8ad6dff96217212b72dbe0d45b3f3af0c255e9b1596c018caf635869db97&network=mainnet
      description: >-
        The PT-wstUSR-29JAN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xcf30228b60d9ec544889f5a77a2fada8e8d19ab921e0d7d35c7d011b54ade4d0&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x5aa4afe7359d5a68d193f03e013d553deb7dbd1f'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xf982e67987ed310641bb33f1e7ebf3a0a2930f6b00d8f6b089440ace18f76c9b&network=mainnet
      description: >-
        The PT-wsrUSD-26FEB2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x545a490f9ab534adf409a2e682bc4098f49952e3'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xe1fea9eb02bc317896351ecac1fc57c9ab58e06630d4510c6fa2cba1fcb0014a&network=mainnet
      description: >-
        The PT-cUSD-29JAN2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0xeeaa924eb3667f30be02db9c55d87566a3f4df7a'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xdeca5331fa55b630026fedf5b2bfa0d384b35dbebd9921832e67ad305f48d8d8&network=mainnet
      description: >-
        The PT-RUSD-26FEB2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0xe8483517077afa11a9b07f849cee2552f040d7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xd174bb7b8dd6ef16b116753b56679932ee13382b94f81bf66a2b37962cb41f56&network=mainnet
      description: >-
        The PT-sUSDE-5FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0xeeaa924eb3667f30be02db9c55d87566a3f4df7a'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb82cb1140daae367c1f39dd6b4ec6a3aaef997764c84634ad8a4114571c15ef3&network=mainnet
      description: >-
        The PT-RUSD-26FEB2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
  yt: []
  lp: []
