name: Morpho
icon: logo.png
category: Money Market
url: https://app.morpho.org/ethereum/borrow
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 1
      address: '0x3eaa0f0f0a5d3d595ae4e4b0d27f439d01c3e7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x9bc98c2f20ac58287ef2c860eea53a2fdc27c17a7817ff1206c0b7840cc7cd79&network=mainnet
      description: >-
        The PT-reUSD-25JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x29fd7180e5cced14ad148c7997e6b6857a8be86e'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x1cfdc0154ae6b9f1887a8250f2582d55606e1a2008e65108fb83dd50a928593e&network=mainnet
      description: >-
        The PT-RLP-9APR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x54bf2659b5cdfd86b75920e93c0844c0364f5166'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2a9a5c436719badcfadbad3ad8e8179a160ded758603eaa03a883f922a1790d3&network=mainnet
      description: >-
        The PT-sNUSD-5MAR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x27b9a0a5bfee98a31eb51e3850250d103a9f8e41673c782defc66aa943af0e65&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xb2f87218f0e2478ba7a2b8be9fe76cbd6f54f8654b9651d4bd1f0ea536674691&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/market?id=0xba8c21d3e47814574a61bee82e7053274f731ad253b24865acab8476fa477ee7&network=mainnet
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 1
      address: '0xaf76b3af3477e4a2cd0b7f80c3152108c19a25e5'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xaac3ffcdf8a75919657e789fa72ab742a7bbfdf5bb0b87e4bbeb3c29bbbbb05c&network=mainnet
      description: >-
        The PT-siUSD-26MAR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2afd063a5af8e050069cfad4da95c81768b85b140bea2bd89e00407b15ce82c8&network=mainnet
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x64b393288ab2a0fe7af6b73a9159493e60ab0605'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x3d353ef0436b85c3b12d53536c19b21c533c046b07c9d92d791a1510e7ef0b74&network=mainnet
      description: >-
        The PT-mAPOLLO-30APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd87169640666649f1e6f92034dca9e4ae748de69'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xca432a8b0f33541cfe164d388823d05b607db43b690d4856f343eec3b42402c0&network=mainnet
      description: >-
        The PT-mHYPER-30APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x9d9874e867b877dd0a3f1eafb8bb1bc54eecc682'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x87a686cc100aabe917f8e1ad58140a1b63f0edbb9650a32c0526718dc610b2d5&network=unichain
      description: >-
        The PT-cUSD-23JUL2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x702b7ec7628de2622e51e1bb34a7e6ad9e95f3a25a2ed361e4ce621f23f5e642&network=mainnet
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0xfd039edc69eac5eaab4a10463fdbcaca75d6eddb1f0e00248d73fc977fb2554b&network=mainnet
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x2fb3713487c7812e7309935b034f40228841666f6b048faf31fd2110ae674f20&network=mainnet
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/market?id=0x5eaaebc81e9e27972ab458811d1b60828e8ab51ef6620f9b3918fd7e68eecec1&network=mainnet
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x606b5c773dc4d6e625c411cf60565f8c30c467d2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xc978f01522ff64adafd91856065d602c56e326a0368b895bd9244d5998e60076&network=mainnet
      description: >-
        The PT-savUSD-14MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x1cdde40e29da213f42a7fa109ccadca372d9ee1b'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x958b40fcd0df023c156ec4a7eb8ffd47985b19d8bb02a36fb0af1bfc837fd605&network=arbitrum
      description: >-
        The PT-USDai-18JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x1cdde40e29da213f42a7fa109ccadca372d9ee1b'
      subtitle: USDT0
      integrationUrl: >-
        https://app.morpho.org/market?id=0x98225f86d3c0673d9b652b12f021f9bc6a09c9ca960680bea23c4de7e2a90f64&network=arbitrum
      description: >-
        The PT-USDai-18JUN2026 is the asset used as collateral in a Morpho
        market with USDT0 as the loan token.
    - chainId: 1
      address: '0x5dbf246b37e1b9ac5d08bb38233d71322ae7d166'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xdf034d0351a4c0af947e1a37ecd5ccbce60d72eac90de6fcad48c74e2869d14c&network=mainnet
      description: >-
        The PT-iUSD-25JUN2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 42161
      address: '0xe46271ecb1d5c7c5134868760f10c18b03021ef1'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xc8455ed78482f7ef016caf0127c7ffd5e643b3b83d08d43e242a63c12358f754&network=arbitrum
      description: >-
        The PT-thBILL-18JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x82b853db31f025858792d8fa969f2a1dc245c179'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0xc2bc5e1e304fb1ea103dcbee37ece3c7e9219fb4b2b19d8ffdf81c39f4fbf180&network=mainnet
      description: >-
        The PT-srNUSD-28MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 42161
      address: '0x07bc5bd6ce9a17f0e7aa91e0adbc9070dcb1d1de'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/market?id=0x50d1b741a63204ce27bdf17e5a9300800c350ecb9278d92d2292a5713ea227e6&network=arbitrum
      description: >-
        The PT-sUSDai-18JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
  yt: []
  lp: []
