name: Morpho
icon: logo.png
metadata:
  pt:
    - chainId: 1
      address: "0x5BaE9a5D67d1CA5b09B14c91935f635CFBF3b685"
      integrationUrl: https://app.morpho.org/market?id=0x8411eeb07c8e32de0b3784b6b967346a45593bfd8baeb291cc209dc195c7b3ad&network=mainnet&morphoPrice=1
      description: >-
        The PT-USD0++-27MAR2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: "0x270d664d2Fc7D962012a787Aec8661CA83DF24EB"
      integrationUrl: https://app.morpho.org/market?id=0x35669bebe1faac708df40050c4841b841e00b3b7a51fb7e091361dd0f3d3b52c&network=mainnet&morphoPrice=1
      description: >-
        The PT-USD0++-31OCT2024 is the asset used as collateral in a Morpho
        market with USDA as the loan token.
    - chainId: 1
      address: "0xf7906F274c174A52d444175729E3fa98f9bde285"
      integrationUrl: https://app.morpho.org/market?id=0xed9e817ac29464b3cc520bf124fb333c330021a8ae768889f414d21df35686e0&network=mainnet&morphoPrice=1
      description: >-
        The PT-ezETH-26DEC2024 is the asset used as collateral in a Morpho
        market with USDA as the loan token.
    - chainId: 1
      address: "0xf7906F274c174A52d444175729E3fa98f9bde285"
      integrationUrl: https://app.morpho.org/market?id=0x2daab4eb520e7eab0a6d432d2edfb11775c9544a6b5e441c2e0f74abcd48f975&network=mainnet&morphoPrice=1
      description: >-
        The PT-USD0++-31OCT2024 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: "0xE00bd3Df25fb187d6ABBB620b3dfd19839947b81"
      integrationUrl: https://app.morpho.org/market?id=0x5e3e6b1e01c5708055548d82d01db741e37d03b948a7ef9f3d4b962648bcbfa7&network=mainnet&morphoPrice=1
      description: >-
        The PT-sUSDE-27MAR2025 is the asset used as collateral in a Morpho
        market with DAI as the loan token.
    - chainId: 1
      address: "0xE00bd3Df25fb187d6ABBB620b3dfd19839947b81"
      integrationUrl: https://app.morpho.org/market?id=0x346afa2b6d528222a2f9721ded6e7e2c40ac94877a598f5dae5013c651d2a462&network=mainnet&morphoPrice=1
      description: >-
        The PT-sUSDE-27MAR2025 is the asset used as collateral in a Morpho
        market with USDC as the loan token.        
    - chainId: 1
      address: "0xAE5099C39f023C91d3dd55244CAFB36225B0850E"
      integrationUrl: https://app.morpho.org/market?id=0x8f46cd82c4c44a090c3d72bd7a84baf4e69ee50331d5deae514f86fe062b0748&network=mainnet&morphoPrice=1
      description: >-
        The PT-sUSDE-24OCT2024 is the asset used as collateral in a Morpho
        market with DAI as the loan token.
    - chainId: 1
      address: "0xEe9085fC268F6727d5D4293dBABccF901ffDCC29"
      integrationUrl: https://app.morpho.org/market?id=0xe37784e5ff9c2795395c5a41a0cb7ae1da4a93d67bfdd8654b9ff86b3065941c&network=mainnet&morphoPrice=1
      description: >-
        The PT-sUSDE-26DEC2024 is the asset used as collateral in a Morpho
        market with DAI as the loan token.
  yt: []
  lp: []
