name: Term
icon: Term_TokenIcon_OnBlue.png
category: 'Money Market'
url: https://www.app.term.finance/auctions
metadata:
  pt:
    - chainId: 43114
      address: '0xb4205a645c7e920bd8504181b1d7f2c5c955c3e7'
      subtitle: USDC
      integrationUrl: https://app.term.finance/auctions
      description: The PT-USDe 25 Sep 2025 is the asset that can be used as collateral in a fixed rate, matched-maturity Term loan with USDC as the loan token.
