name: Avalon Finance
icon: logo.png
metadata:
  pt:
    # Ethereum PT-corn-SolvBTC.BBN-26DEC2024
    - chainId: 1
      address: '0x23e479ddcda990e8523494895759bd98cd2fdbf6'
      integrationUrl: >-
        https://app.avalonfinance.xyz/reserve-overview/?underlyingAsset=0x23e479ddcda990e8523494895759bd98cd2fdbf6&marketName=proto_mainnet_v3
      description: Supply PT on Avalon Finance to receive extra yield and avalon points.
    # Ethereum PT-LBTC-27MAR2025
    - chainId: 1
      address: '0xec5a52c685cc3ad79a6a347abace330d69e0b1ed'
      integrationUrl: >-
        https://app.avalonfinance.xyz/reserve-overview/?underlyingAsset=0xec5a52c685cc3ad79a6a347abace330d69e0b1ed&marketName=proto_ebtc_mainnet_innovation
      description: Supply PT on Avalon Finance to receive extra yield and avalon points.
    # Ethereum PT-EBTC-26DEC2024
    - chainId: 1
      address: '0xb997b3418935a1df0f914ee901ec83927c1509a0'
      integrationUrl: >-
        https://app.avalonfinance.xyz/reserve-overview/?underlyingAsset=0xb997b3418935a1df0f914ee901ec83927c1509a0&marketName=proto_ebtc_mainnet_innovation
      description: Supply PT on Avalon Finance to receive extra yield and avalon points.
    # Ethereum PT-cornLBTC-26DEC2024
    - chainId: 1
      address: '0x332a8ee60edff0a11cf3994b1b846bbc27d3dcd6'
      integrationUrl: >-
        https://app.avalonfinance.xyz/reserve-overview/?underlyingAsset=0x332a8ee60edff0a11cf3994b1b846bbc27d3dcd6&marketName=proto_ebtc_mainnet_innovation
      description: Supply PT on Avalon Finance to receive extra yield and avalon points.
    # BSC PT-SolvBTC.BBN-27MAR2025
    - chainId: 56
      address: '0x541b5eeac7d4434c8f87e2d32019d67611179606'
      integrationUrl: >-
        https://app.avalonfinance.xyz/reserve-overview/?underlyingAsset=0x541b5eeac7d4434c8f87e2d32019d67611179606&marketName=proto_bsc_v3
      description: Supply PT on Avalon Finance to receive extra yield and avalon points.
  yt: []
  lp: []
